moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - denso_joint_trajectory_controller

  denso_joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - cobotta_pro_joint_1
      - cobotta_pro_joint_2
      - cobotta_pro_joint_3
      - cobotta_pro_joint_4
      - cobotta_pro_joint_5
      - cobotta_pro_joint_6
