moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - denso_joint_trajectory_controller
    - onrobot_rg6

  denso_joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - cobotta_pro_joint_1
      - cobotta_pro_joint_2
      - cobotta_pro_joint_3
      - cobotta_pro_joint_4
      - cobotta_pro_joint_5
      - cobotta_pro_joint_6

  onrobot_rg6:
    action_ns: gripper_cmd
    type: ParallelGripperCommand
    default: true
    joints:
      - rg6_finger_joint


trajectory_execution:
  allowed_execution_duration_scaling: 2.0
  allowed_goal_duration_margin: 5.0
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: true