# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    denso_joint_group_position_controller:
      type: position_controllers/JointGroupPositionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - cobotta_pro_joint_1
      - cobotta_pro_joint_2
      - cobotta_pro_joint_3
      - cobotta_pro_joint_4
      - cobotta_pro_joint_5
      - cobotta_pro_joint_6
    command_interfaces:
      []
    state_interfaces:
      []
    allow_nonzero_velocity_at_trajectory_end: true
denso_joint_group_position_controller:
  ros__parameters:
    joints:
      - cobotta_pro_joint_1
      - cobotta_pro_joint_2
      - cobotta_pro_joint_3
      - cobotta_pro_joint_4
      - cobotta_pro_joint_5
      - cobotta_pro_joint_6