controller_manager:
  ros__parameters:
    update_rate: 125 # Hz

    denso_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    denso_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    denso_joint_group_position_controller:                                                                                                                                                                                
      type: position_controllers/JointGroupPositionController

    onrobot_rg6:
      type: parallel_gripper_action_controller/GripperActionController
      

denso_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var namespace)joint_1
      - $(var namespace)joint_2
      - $(var namespace)joint_3
      - $(var namespace)joint_4
      - $(var namespace)joint_5
      - $(var namespace)joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 500
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: true
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

denso_joint_group_position_controller:                                                                                                                                                                                    
  ros__parameters:                                                                                                                                                                                                        
    joints:                                                                                                                                                                                                               
      - cobotta_pro_joint_1                                                                                                                                                                                               
      - cobotta_pro_joint_2                                                                                                                                                                                               
      - cobotta_pro_joint_3                                                                                                                                                                                               
      - cobotta_pro_joint_4                                                                                                                                                                                               
      - cobotta_pro_joint_5                                                                                                                                                                                               
      - cobotta_pro_joint_6                                                                                                                                                                                               
    interface_name: position

onrobot_rg6:
  ros__parameters:
    joint: rg6_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity