# Copyright (c) 2026, Fraunhofer IPA.
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""The Denso Cobotta Pro (CVRB0609) + OnRobot RG6 as an Isaac Lab articulation.

This is the only module to touch when retuning the robot. It declares the
actuators and assembles the :class:`ArticulationCfg` that a scene drops into
``InteractiveSceneCfg`` as ``robot``. Joint names and the home pose live in
:mod:`.joints`.

The URDF it loads is generated by ``scripts/build_urdf_asset.py`` from the
flattened description ``techtory_cobotta_isaacsim`` carries, and committed under
``assets/``, so nothing here needs a ROS environment. Isaac Lab converts it to
USD on first use and caches the result.

``denso_robot_descriptions`` authors placeholder dynamics for the CVRB0609:
every arm link is 1 kg with an identity inertia tensor and every joint carries
``effort="1"``. The actuator gains below are therefore chosen to hold the arm,
not to model the real drive train -- the same call ``techtory_cobotta_mujoco``
made, and its ``config/actuators.yaml`` is where the arm numbers come from.
"""

from __future__ import annotations

import math
from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg
from isaaclab_physx.sim.schemas import (
    PhysxArticulationRootPropertiesCfg,
    PhysxRigidBodyPropertiesCfg,
)

from techtory_cobotta_isaaclab.robot.joints import (
    FT_JOINT,
    GRIPPER_JOINTS,
    HOME_POSE,
    MOUNT_POS,
    MOUNT_ROT,
)

__all__ = [
    "ASSETS_DIR",
    "COBOTTA_CFG",
    "COBOTTA_URDF",
]

##
# URDF and assets.
##

ASSETS_DIR: Path = Path(__file__).parent / "assets"
COBOTTA_URDF: Path = ASSETS_DIR / "cobotta_rg6.urdf"

if not COBOTTA_URDF.exists():  # pragma: no cover - a broken checkout, not a code path
    raise FileNotFoundError(f"{COBOTTA_URDF} is missing. Generate it with:\n  python scripts/build_urdf_asset.py")

##
# Actuators.
##

# Stiffness matters more than it looks. The URDF importer marks a joint
# position-driven but assigns no gain, so an arm left at the import default has
# no holding torque and folds under gravity. The effort limits replace the
# URDF's placeholder 1 N.m, which cannot hold the arm up at all. Joints 2 and 3
# carry the most gravity load (shoulder and elbow), hence the higher limits.
_ARM_ACTUATOR = ImplicitActuatorCfg(
    joint_names_expr=["cobotta_pro_joint_[1-6]"],
    effort_limit_sim={
        "cobotta_pro_joint_2": 600.0,
        "cobotta_pro_joint_3": 400.0,
        "cobotta_pro_joint_[1456]": 300.0,
    },
    stiffness=4000.0,
    damping=200.0,
    armature=0.01,
)

# All six RG6 joints are driven: the <mimic> coupling is stripped by the asset
# builder and the gripper action writes `multiplier * q` to each of them.
#
# Tuning is techtory_cobotta_isaacsim/spawners/spawn_robot.py's, converted to
# SI. That file writes USD drive gains, which are authored PER DEGREE (3.0 and
# 0.1); Isaac Lab gains are per radian, so they are multiplied by 180/pi here.
# 5 N.m on finger_joint is ~60 N of finger force through the RG6's 0.080 m
# lever, the middle of the datasheet's 25-120 N band -- the gripper should hold
# the hammer, not crush it. Armature and joint friction stop the light (50 g)
# linkage links from ringing, and the speed cap keeps closing gentle.
_DEG_PER_RAD = 180.0 / math.pi
_GRIPPER_ACTUATOR = ImplicitActuatorCfg(
    joint_names_expr=list(GRIPPER_JOINTS),
    effort_limit_sim=5.0,
    velocity_limit_sim=0.6,
    stiffness=3.0 * _DEG_PER_RAD,
    damping=0.1 * _DEG_PER_RAD,
    armature=0.15,
    friction=0.4,
)

# The locked wrist joint (see joints.FT_JOINT). Its +/-1 mrad limits do the
# locking; this drive only centres it so it does not rest against one stop.
# Deliberately soft: a stiff drive on the light RG6 about the flange axis would
# be the highest-frequency mode in the robot and ring at the 5 ms step, and that
# ringing would show up in the very wrench this joint exists to report.
_WRIST_LOCK_ACTUATOR = ImplicitActuatorCfg(
    joint_names_expr=[FT_JOINT],
    effort_limit_sim=50.0,
    stiffness=100.0,
    damping=5.0,
    armature=0.1,
)

##
# The articulation.
##

COBOTTA_CFG = ArticulationCfg(
    spawn=sim_utils.UrdfFileCfg(
        asset_path=str(COBOTTA_URDF),
        # Bolted to the base plate. The cell, not the robot, is what stands on
        # the floor.
        fix_base=True,
        # MUST stay False. The tool frame cobotta_pro_tool0 hangs off the RG6
        # base_link through a fixed joint, and merging would delete it -- the
        # EE pose observation reads that body. (The wrist F/T joint itself is a
        # locked revolute, see joints.FT_JOINT, so merging cannot fold it away
        # any more; keeping every body separate also keeps the body list
        # identical across PhysX and Newton.) tests/test_robot_cfg.py asserts it.
        merge_fixed_joints=False,
        merge_mesh=False,
        collision_from_visuals=False,
        collision_type="Convex Hull",
        self_collision=False,
        # Self-collisions OFF, set on the PhysX side explicitly: the URDF
        # converter's `self_collision=False` writes only
        # `newton:selfCollisionEnabled`, and PhysX reads
        # `physxArticulation:enabledSelfCollisions`, which otherwise defaults to
        # ON. The RG6 knuckles and fingers overlap by design (it is a closed
        # four-bar held open by the joint coupling), so with self-collision on
        # the linkage jams -- the same reason spawn_robot.py calls
        # disable_articulation_self_collisions().
        articulation_props=PhysxArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=32,
            solver_velocity_iteration_count=4,
        ),
        rigid_props=PhysxRigidBodyPropertiesCfg(
            max_depenetration_velocity=1.0,
            # techtory_cobotta_isaacsim found disableGravity=True on the RG6
            # links, and the wrist wrench then reads zero. Gravity on is what
            # makes the F/T sensor see the tool weight.
            disable_gravity=False,
        ),
        joint_drive=sim_utils.UrdfConverterCfg.JointDriveCfg(
            # Gains deliberately left None: the actuator configs above own every
            # drive gain, and setting them in both places means two files claim
            # one number and the later write silently wins.
            target_type="position",
            drive_type="force",
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=MOUNT_POS,
        rot=MOUNT_ROT,
        # The patterns must PARTITION the joints: Isaac Lab's
        # resolve_matching_names_values raises on a joint matched twice.
        joint_pos={**HOME_POSE, **{name: 0.0 for name in GRIPPER_JOINTS}, FT_JOINT: 0.0},
        joint_vel={".*": 0.0},
    ),
    actuators={
        "arm": _ARM_ACTUATOR,
        "gripper": _GRIPPER_ACTUATOR,
        "wrist_lock": _WRIST_LOCK_ACTUATOR,
    },
    soft_joint_pos_limit_factor=1.0,
)
"""The Cobotta Pro + RG6 articulation, ready for ``InteractiveSceneCfg``."""
